### ISSUE TITLE
Program finishing but isolate times out on wall clock?

### ISSUE THREAD

**Issue by tomsharratt** [ioi/isolate#104] opened 2021-08-09 01:33 UTC
command:

`isolate --cg -b 1 -t 3 -x 4 -w 6 -p4 -k 1000 -f 1000 -M a --cg-timing -d /app/packages -E "PATH=/app/packages/node/16.3.0/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:." --run -- /bin/bash run index.js`

the run script is `node "$@"`

Manifest:
```
status:TO
message:Time limit exceeded (wall clock)
killed:1
time:0.008
time-wall:6.071
max-rss:884
csw-voluntary:4
csw-forced:0
cg-mem:1608
```

Why is it running in 0.008 but hanging for 6 seconds and being killed by the time wall? Also, if I don't set a time wall it just hangs indefinitely.

**Comment by gollux** [comment] 2022-01-26 20:04
Can you try to strace it as root to see what's happening?

Does the problem occur without `--cg`?

**Comment by gollux** [comment] 2022-08-08 10:40
Since nobody replied and I am unable to reproduce the problem, I am closing the issue. Feel free to re-open it.

**Closed by gollux** 2022-08-08 10:40 UTC
