### ISSUE TITLE
--fsize for stdout

### ISSUE THREAD

**Issue by hermanzdosilovic** [ioi/isolate#19] opened 2016-11-14 19:49 UTC
When using `--fsize` (`-f`) flag programs output to stdout is also being limited to specified value (eq. 1MB). Is this expected behaviour and if it is why is it expected behaviour?

Thanks!

**Comment by gollux** [comment] 2016-11-14 20:44
If your stdout is a file then yes, it is expected behavior, because `--fsize` affects all files. If it is not a file, let me know, it could be a bug.

**Comment by hermanzdosilovic** [comment] 2016-11-15 12:26
In my program I don't open any files. I just specified output with `-o` flag in isolate.

I noticed that these two commands limit file size to 1MB:
```
$ isolate --fsize 1 -i input.txt -o output.txt --run -- a.out
$ isolate --fsize 1 -i input.txt --run -- a.out > output.txt
```

But this one doesn't:
```
$ isolate --fsize 1 -i input.txt --run -- a.out | dd of=output.txt
```

Also, on my machine this command sometimes generates output.txt, and sometimes doesn't:
```
$ isolate --fsize 1 -i input.txt --run -- a.out | tee output.txt
```

**Comment by gollux** [comment] 2016-11-15 13:25
In the third example, the output file is generated by "dd", which runs outside the sandbox, so it is not limited by the sandbox in any way. On the contrary, in the first two examples, the file is written to by the program running inside the sandbox, so the limit applies.

The fourth example should behave deterministically. If the output file is not generated, does any error message appear?

**Comment by hermanzdosilovic** [comment] 2016-11-15 13:32
I don't get any error messages for fourth example.

**Comment by gollux** [comment] 2016-11-15 21:28
> I don't get any error messages for fourth example.

Is the experiment repeatable?

**Comment by hermanzdosilovic** [comment] 2016-11-15 22:14
Why it wouldn't be? :smile: Yes, I tried that running this many times. Can you try it on your machine? Any program that outputs something to stdout will do the job.

**Comment by gollux** [comment] 2016-11-17 11:35
I just ran the following test:

`set -e ; while true ; do rm -f /tmp/1 && bin/isolate --fsize 1 --run -- /bin/echo brequequex | tee /tmp/1 && est -s /tmp/1 ; done`

Even after several thousand tries, it did not fail. Also, I see no reason why `tee` not creating a file when running outside sandbox could be related to isolate in any way.

I am closing this issue, but if you have any other data confirming the problem, feel free to re-open it.

**Closed by gollux** 2016-11-17 11:35 UTC
