### ISSUE TITLE
Inconsistent signal handling

### ISSUE THREAD

**Issue by Zopieux** [ioi/isolate#37] opened 2017-10-22 17:39 UTC
### Correct signal handling
```c
int main(void) {
    return 1 / 0;
}
```
```console
$ /var/lib/isolate/4/box/a.out
[1]    18386 floating point exception (core dumped)  /var/lib/isolate/4/box/a.out
```
```console
$ isolate --box-id 4 --cg --run -- /box/a.out
Caught fatal signal 8
```
Result: SIGFPE is correctly caught by isolate.

### Incorrect signal handling
```c
#include <signal.h>
int main(void) {
    return raise(SIGFPE);
}
```
```console
$ /var/lib/isolate/4/box/a.out
[1]    18433 floating point exception (core dumped)  /var/lib/isolate/4/box/a.out
```
```console
$ isolate --box-id 4 --cg --run -- /box/a.out
OK (0.002 sec real, 0.064 sec wall)
```
Result: SIGFPE is raised but nothing is caught by isolate, as seen by the *OK* message.
I have the same result with other signals (eg. SIGINT). Always OK.

Any idea why this would happen? Is there a bug in isolate or is this expected behavior?

**Comment by Zopieux** [comment] 2017-10-22 17:48
I thought this may be related to https://github.com/ioi/isolate/blob/master/isolate.c#L272 but SIGKILL is not in the table, yet it still *OK*ays out.

**Comment by gollux** [comment] 2017-10-22 18:10
Hello!

In control group mode, the sandboxed process is effectively an init process
of its container and the usual exceptions for delivering signals to init apply
(well, at least with respect to signals which came from the inside of the
container; SIGKILL sent from the parent container is always unblockable).

Therefore a SIGFPE sent to the same process is not fatal, while SIGFPE
automatically generated by division by zero is fatal.

For SIGFPE, it is probably harmless, but I suspect that ignoring raise(SIGABRT)
could be less pleasant as it is used by libstdc++ when an unhandled exception
is thrown.

I will think about it...

**Comment by hermanzdosilovic** [comment] 2017-10-22 20:02
I can reproduce both examples: [first](https://ide.judge0.com/?AHN3oorpFTt5lsa4pUtJd27gYNT9), [second](https://ide.judge0.com/?AHzIEWhUVakmFBSQT4maqP8b4AMe).

**Comment by Leo1003** [comment] 2017-11-03 16:12
I have the same problem too. Because the process is the init process in the namespace, it won't receive signals (even the signal is from the parent namespace) unless the init process register the signal handler. This problem made me hard to check if the process was killed by signals like SIGABRT, SIGXCPU, SIGXFSZ, and so on...

**Comment by gollux** [comment] 2018-02-22 06:18
In the proxy branch (to be merged after some review), we added an extra process serving as init in the namespace, so that the sandboxed process should have its signals delivered properly.

**Closed** 2018-02-22 09:25 UTC
